# -*- coding: utf-8 -*-
"""R1_sigma_clipping_exo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vne4pehxdb0DV0tSGRR0T69UZ4KpC_pE

===========================================================
Nombre del programa : Sigma-Clipping aplicado en base de
                      datos de Exoplanetas
Archivo             : R1_sigma_clipping_exo.py
Autor               : Jose Miguel Mata Lopez
Fecha               : 13 de marzo de 2026
Version             : 1.0
Descripcion         :
    Este notebook contiene código para aplicar sigma clipp-
    ing a una base de datos de exoplanetas extraida de
    exoplanetas.eu.

Librerias utilizadas:
    - numpy
    - pandas
    - matplotlib
===========================================================
"""

# Importamos librerias
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Cargamos la base de datos
df = pd.read_csv('/content/drive/MyDrive/Exoplanetas/base_datos.csv')
radius_jup = np.array(df['radius'])
mass_jup = np.array(df['mass'])

# Eliminamos el valor mas peuqueño segun el radio y masa
idx = np.argmin(radius_jup)
radius_jup = np.delete(radius_jup, idx)
mass_jup = np.delete(mass_jup, idx)

# Valores de la masa de la Tierra y de Júpiter en kg
e_mass = 5.97217e24
j_mass = 1898.125e24

# Proporción entre la masa de Júpiter y masa de la tierra
mass_prop = j_mass / e_mass

# Valores del radio de la Tierra y de Júpiter en km
e_radius = 6378.1366
j_radius = 71492.0
# Proporción entre el radio de Júpiter y radio de la tierra
radius_prop = j_radius / e_radius

print("Proporción MJ:MT: ", mass_prop)
print("Proporción RJ:RT: ", radius_prop)
print(0.414*mass_prop)

# Constantes de Müller
b0_m1 = np.log10(1.02)
b1_m1 = 0.27

# Definimos los límites de masa reportados en Muller et al.
lim_inf_masa_muller = np.log10(4.37)
lim_sup_masa_muller = np.log10(127)

# Convertimos los valores de columnas radio y masa en términos
# de los valores de la tierra
mass_earth = np.log10(mass_jup * mass_prop)
radius_earth = np.log10(radius_jup * radius_prop)

# Definimos función para calcular ajuste
def ajuste(x,y):
  sum_1 = 0
  sum_2 = 0
  for i in range(len(x)):
    sum_1 += (x[i] - np.mean(x))*(y[i] - np.mean(y))
    sum_2 += (x[i] - np.mean(x))**2

  b1 = sum_1/sum_2
  b0 = np.mean(y) - b1*np.mean(x)
  return b1, b0

# Definimos función para evaluar ajuste
def calidad_ajuste(x, y, b0, b1):
  stcc = 0
  sce = 0

  for i in range(len(x)):
    stcc += (y[i] - np.mean(y))**2
    sce += (y[i] - b0 - (b1*x[i]))**2
  return 1 - (sce/stcc)

def sigma_clipping(x, y, b0, b1, param):
  # Aplicamos sigma clipping
  clipped_x = np.array([])
  clipped_y = np.array([])
  residuos = np.array([])
  for i in range(len(y)):
    residuos = np.append(residuos, y[i] - b0 - (b1*x[i]))

  for i in range(len(x)):
    if abs(y[i] - b0 - (b1*x[i])) < param*np.std(residuos):
      clipped_y = np.append(clipped_y, y[i])
      clipped_x = np.append(clipped_x, x[i])

  return clipped_x, clipped_y

def clasificacion_regiones(lim_inf, lim_sup, x, y):
  clase1_masa = np.array([])
  clase1_radio = np.array([])
  clase2_masa = np.array([])
  clase2_radio = np.array([])
  clase3_masa = np.array([])
  clase3_radio = np.array([])
  for i in range(len(x)):
      if x[i] < lim_inf:
          clase1_masa = np.append(clase1_masa, x[i])
          clase1_radio = np.append(clase1_radio, y[i])
      elif lim_inf < x[i] < lim_sup:
          clase2_masa = np.append(clase2_masa, x[i])
          clase2_radio = np.append(clase2_radio, y[i])
      else:
          clase3_masa = np.append(clase3_masa, x[i])
          clase3_radio = np.append(clase3_radio, y[i])

  return clase1_masa, clase1_radio, clase2_masa, clase2_radio, clase3_masa, clase3_radio

def interseccion(b0_2, b1_2, b0_1, b1_1):
    x_interseccion = (b0_2 - b0_1) / (b1_1 - b1_2)
    return x_interseccion

iteraciones = 2
param = 2

# Dividimos clases
clase1_masa_orig, clase1_radio_orig, clase2_masa_orig, clase2_radio_orig, clase3_masa_orig, clase3_radio_orig = clasificacion_regiones(
    lim_inf_masa_muller, lim_sup_masa_muller, mass_earth, radius_earth)

# Hacemos ajuste
b1_c1_orig, b0_c1_orig = ajuste(clase1_masa_orig, clase1_radio_orig)

b1_c2_orig, b0_c2_orig = ajuste(clase2_masa_orig, clase2_radio_orig)

b1_c3_orig, b0_c3_orig = ajuste(clase3_masa_orig, clase3_radio_orig)

r2_c1_orig = calidad_ajuste(clase1_masa_orig, clase1_radio_orig, b0_c1_orig, b1_c1_orig)
r2_c2_orig = calidad_ajuste(clase2_masa_orig, clase2_radio_orig, b0_c2_orig, b1_c2_orig)
r2_c3_orig = calidad_ajuste(clase3_masa_orig, clase3_radio_orig, b0_c3_orig, b1_c3_orig)

print("Calidad| Clase 1: ", r2_c1_orig, "Clase 2: ", r2_c2_orig, "Clase 3: ", r2_c3_orig)

clipped_clase1_masa = clase1_masa_orig
clipped_clase1_radio = clase1_radio_orig

clipped_clase2_masa = clase2_masa_orig
clipped_clase2_radio = clase2_radio_orig

clipped_clase3_masa = clase3_masa_orig
clipped_clase3_radio = clase3_radio_orig

b0_c1_clipped = b0_c1_orig
b1_c1_clipped = b1_c1_orig

b0_c2_clipped = b0_c2_orig
b1_c2_clipped = b1_c2_orig

b0_c3_clipped = b0_c3_orig
b1_c3_clipped = b1_c3_orig

calidades_c1 = np.array([])
calidades_c2 = np.array([])
calidades_c3 = np.array([])

calidades_c1 = np.append(calidades_c1, r2_c1_orig)
calidades_c2 = np.append(calidades_c2, r2_c2_orig)
calidades_c3 = np.append(calidades_c3, r2_c3_orig)

valor_iter = np.array([])
valor_iter = np.append(valor_iter, 0)

print(f"b0,b1: C1 = {b0_c1_orig:.3f},{b1_c1_orig:.3f} | b0,b1: C2 = {b0_c2_orig:.3f},{b1_c2_orig:.3f} | b0,b1: C3 = {b0_c3_orig:.3f},{b1_c3_orig:.3f}")

for i in range(iteraciones):
  clipped_clase1_masa, clipped_clase1_radio = sigma_clipping(clipped_clase1_masa, clipped_clase1_radio, b0_c1_clipped, b1_c1_clipped, param)
  clipped_clase2_masa, clipped_clase2_radio = sigma_clipping(clipped_clase2_masa, clipped_clase2_radio, b0_c2_clipped, b1_c2_clipped, param)
  clipped_clase3_masa, clipped_clase3_radio = sigma_clipping(clipped_clase3_masa, clipped_clase3_radio, b0_c3_clipped, b1_c3_clipped, param)

  b1_c1_clipped, b0_c1_clipped = ajuste(clipped_clase1_masa, clipped_clase1_radio)
  b1_c2_clipped, b0_c2_clipped = ajuste(clipped_clase2_masa, clipped_clase2_radio)
  b1_c3_clipped, b0_c3_clipped = ajuste(clipped_clase3_masa, clipped_clase3_radio)

  r2_c1_clipped = calidad_ajuste(clipped_clase1_masa, clipped_clase1_radio, b0_c1_clipped, b1_c1_clipped)
  r2_c2_clipped = calidad_ajuste(clipped_clase2_masa, clipped_clase2_radio, b0_c2_clipped, b1_c2_clipped)
  r2_c3_clipped = calidad_ajuste(clipped_clase3_masa, clipped_clase3_radio, b0_c3_clipped, b1_c3_clipped)

  calidades_c1 = np.append(calidades_c1, r2_c1_clipped)
  calidades_c2 = np.append(calidades_c2, r2_c2_clipped)
  calidades_c3 = np.append(calidades_c3, r2_c3_clipped)

  valor_iter = np.append(valor_iter, i+1)


  print(f"IT {i+1} | Calidad R^2 | Clase 1: {r2_c1_clipped:.4f} | Clase 2: {r2_c2_clipped:.4f} | Clase 3: {r2_c3_clipped:.4f}| Valores Eliminados: C1: {len(clase1_masa_orig)-len(clipped_clase1_masa)} | C2: {len(clase2_masa_orig)-len(clipped_clase2_masa)} | C3: {len(clase3_masa_orig)-len(clipped_clase3_masa)} | b0,b1: C1 = {b0_c1_clipped:.3f},{b1_c1_clipped:.3f} | b0,b1: C2 = {b0_c2_clipped:.3f},{b1_c2_clipped:.3f} | b0,b1: C3 = {b0_c3_clipped:.3f},{b1_c3_clipped:.3f}")

mass_earth_clipped = np.concatenate((clipped_clase1_masa, clipped_clase2_masa, clipped_clase3_masa))
radius_earth_clipped = np.concatenate((clipped_clase1_radio, clipped_clase2_radio, clipped_clase3_radio))

plt.figure(figsize=(10,6))

# Graficamos los puntos para cada planeta
plt.scatter(10**mass_earth, 10**radius_earth, alpha=0.5, s=10, color='red', label='Original')
plt.scatter(10**mass_earth_clipped, 10**radius_earth_clipped, alpha=0.5, s=10, color='royalblue', label='Clipped')

# Se asignan nombres a los ejes de la gráfica
plt.xlabel(f"Mass (M⊕)")
plt.ylabel("Radius (R⊕)")
plt.title(f"Sigma Clipping {param}σ, iteraciones: {iteraciones}")

plt.legend()
plt.xscale('log')
plt.yscale('log')

plt.show()

print(f"Total de valores eliminados: {len(mass_earth)-len(mass_earth_clipped)}")
print("Datos finales: ", len(mass_earth_clipped))

# Inicializamos nuestra figura
plt.figure(figsize=(10,6))

# Graficamos los puntos para cada planeta
#plt.scatter(valor_iter, calidades_c1, alpha=0.5, s=10, color='red', label='R^2:C1')
plt.plot(valor_iter, calidades_c1, color='red', linestyle='-', zorder=1, label='R^2:C1', marker='o')

#plt.scatter(valor_iter, calidades_c2, alpha=0.5, s=10, color='blue', label='R^2:C2')
plt.plot(valor_iter, calidades_c2, color='blue', linestyle='-', zorder=1, label='R^2:C2', marker='o')

plt.plot(valor_iter, calidades_c3, color='green', linestyle='-', zorder=1, label='R^2:C3', marker='o')

# Se asignan nombres a los ejes de la gráfica
plt.xlabel("Iteracion")
plt.ylabel("R^2")
plt.title("R^2")

plt.legend()

plt.show()

iteraciones_inter = 10

tabla_resultados = []

b1_c1_interseccion = b1_c1_clipped
b0_c1_interseccion = b0_c1_clipped

b1_c2_interseccion = b1_c2_clipped
b0_c2_interseccion = b0_c2_clipped

b1_c3_interseccion = b1_c3_clipped
b0_c3_interseccion = b0_c3_clipped

nueva_clase1_masa = clipped_clase1_masa
nueva_clase1_radio = clipped_clase1_radio

nueva_clase2_masa = clipped_clase2_masa
nueva_clase2_radio = clipped_clase2_radio

nueva_clase3_masa = clipped_clase3_masa
nueva_clase3_radio = clipped_clase3_radio

lim_inf_masa = interseccion(b0_c2_clipped, b1_c2_clipped, b0_c1_clipped, b1_c1_clipped)
lim_sup_masa = interseccion(b0_c3_clipped, b1_c3_clipped, b0_c2_clipped, b1_c2_clipped)

# Para graficar
b0_c1_inter = np.array([])
b0_c2_inter = np.array([])
b0_c3_inter = np.array([])

b1_c1_inter = np.array([])
b1_c2_inter = np.array([])
b1_c3_inter = np.array([])

calidades_c1_inter = np.array([])
calidades_c2_inter = np.array([])
calidades_c3_inter = np.array([])

limites_inf_inter = np.array([])
limites_sup_inter = np.array([])


calidades_c1_inter = np.append(calidades_c1_inter, r2_c1_orig)
calidades_c2_inter = np.append(calidades_c2_inter, r2_c2_orig)
calidades_c3_inter = np.append(calidades_c3_inter, r2_c3_orig)

calidades_c1_inter = np.append(calidades_c1_inter, r2_c1_clipped)
calidades_c2_inter = np.append(calidades_c2_inter, r2_c2_clipped)
calidades_c3_inter = np.append(calidades_c3_inter, r2_c3_clipped)


b0_c1_inter = np.append(b0_c1_inter, b0_c1_orig)
b1_c1_inter = np.append(b1_c1_inter, b1_c1_orig)

b0_c2_inter = np.append(b0_c2_inter, b0_c2_orig)
b1_c2_inter = np.append(b1_c2_inter, b1_c2_orig)

b0_c3_inter = np.append(b0_c3_inter, b0_c3_orig)
b1_c3_inter = np.append(b1_c3_inter, b1_c3_orig)


b0_c1_inter = np.append(b0_c1_inter, b0_c1_clipped)
b1_c1_inter = np.append(b1_c1_inter, b1_c1_clipped)

b0_c2_inter = np.append(b0_c2_inter, b0_c2_clipped)
b1_c2_inter = np.append(b1_c2_inter, b1_c2_clipped)

b0_c3_inter = np.append(b0_c3_inter, b0_c3_clipped)
b1_c3_inter = np.append(b1_c3_inter, b1_c3_clipped)


limites_inf_inter = np.append(limites_inf_inter, lim_inf_masa_muller)
limites_sup_inter = np.append(limites_sup_inter, lim_sup_masa_muller)

limites_inf_inter = np.append(limites_inf_inter, lim_inf_masa)
limites_sup_inter = np.append(limites_sup_inter, lim_sup_masa)



valor_iter_inter = np.array([])
valor_iter_inter = np.append(valor_iter_inter, -1)
valor_iter_inter = np.append(valor_iter_inter, 0)

tabla_resultados.append({
    "Iteracion": "Original",
    "R2_C1": r2_c1_orig,
    "R2_C2": r2_c2_orig,
    "R2_C3": r2_c3_orig,
    "Lim_inf": 10**lim_inf_masa_muller,
    "Lim_sup": 10**lim_sup_masa_muller,
    "b0_C1": b0_c1_orig,
    "b1_C1": b1_c1_orig,
    "b0_C2": b0_c2_orig,
    "b1_C2": b1_c2_orig,
    "b0_C3": b0_c3_orig,
    "b1_C3": b1_c3_orig
    })
tabla_resultados.append({
    "Iteracion": "Clipped",
    "R2_C1": r2_c1_clipped,
    "R2_C2": r2_c2_clipped,
    "R2_C3": r2_c3_clipped,
    "Lim_inf": 10**lim_inf_masa,
    "Lim_sup": 10**lim_sup_masa,
    "b0_C1": b0_c1_clipped,
    "b1_C1": b1_c1_clipped,
    "b0_C2": b0_c2_clipped,
    "b1_C2": b1_c2_clipped,
    "b0_C3": b0_c3_clipped,
    "b1_C3": b1_c3_clipped
    })


print(f"Original || Calidad R^2 | Clase 1: {r2_c1_orig:.4f} | Clase 2: {r2_c2_orig:.4f} | Clase 3: {r2_c3_orig:.4f} || Puntos de corte: {10**lim_inf_masa_muller:.3f},{10**lim_sup_masa_muller:.3f} || b0,b1: C1 = {b0_c1_orig:.3f},{b1_c1_orig:.3f} | b0,b1: C2 = {b0_c2_orig:.3f},{b1_c2_orig:.3f} | b0,b1: C3 = {b0_c3_orig:.3f},{b1_c3_orig:.3f}")
print(f"Clipped  || Calidad R^2 | Clase 1: {r2_c1_clipped:.4f} | Clase 2: {r2_c2_clipped:.4f} | Clase 3: {r2_c3_clipped:.4f} || Puntos de corte: {10**lim_inf_masa:.3f},{10**lim_sup_masa:.3f} || b0,b1: C1 = {b0_c1_clipped:.3f},{b1_c1_clipped:.3f} | b0,b1: C2 = {b0_c2_clipped:.3f},{b1_c2_clipped:.3f} | b0,b1: C3 = {b0_c3_clipped:.3f},{b1_c3_clipped:.3f}")

for i in range(iteraciones_inter):

  nueva_clase1_masa, nueva_clase1_radio, nueva_clase2_masa, nueva_clase2_radio, nueva_clase3_masa, nueva_clase3_radio = clasificacion_regiones(
    lim_inf_masa, lim_sup_masa, mass_earth_clipped, radius_earth_clipped)

  b1_c1_interseccion, b0_c1_interseccion = ajuste(nueva_clase1_masa, nueva_clase1_radio)
  b1_c2_interseccion, b0_c2_interseccion = ajuste(nueva_clase2_masa, nueva_clase2_radio)
  b1_c3_interseccion, b0_c3_interseccion = ajuste(nueva_clase3_masa, nueva_clase3_radio)

  lim_inf_masa = interseccion(b0_c2_interseccion, b1_c2_interseccion, b0_c1_interseccion, b1_c1_interseccion)
  lim_sup_masa = interseccion(b0_c3_interseccion, b1_c3_interseccion, b0_c2_interseccion, b1_c2_interseccion)

  r2_c1_new = calidad_ajuste(nueva_clase1_masa, nueva_clase1_radio, b0_c1_interseccion, b1_c1_interseccion)
  r2_c2_new = calidad_ajuste(nueva_clase2_masa, nueva_clase2_radio, b0_c2_interseccion, b1_c2_interseccion)
  r2_c3_new = calidad_ajuste(nueva_clase3_masa, nueva_clase3_radio, b0_c3_interseccion, b1_c3_interseccion)

  calidades_c1_inter = np.append(calidades_c1_inter, r2_c1_new)
  calidades_c2_inter = np.append(calidades_c2_inter, r2_c2_new)
  calidades_c3_inter = np.append(calidades_c3_inter, r2_c3_new)

  b0_c1_inter = np.append(b0_c1_inter, b0_c1_interseccion)
  b1_c1_inter = np.append(b1_c1_inter, b1_c1_interseccion)

  b0_c2_inter = np.append(b0_c2_inter, b0_c2_interseccion)
  b1_c2_inter = np.append(b1_c2_inter, b1_c2_interseccion)

  b0_c3_inter = np.append(b0_c3_inter, b0_c3_interseccion)
  b1_c3_inter = np.append(b1_c3_inter, b1_c3_interseccion)

  limites_inf_inter = np.append(limites_inf_inter, lim_inf_masa)
  limites_sup_inter = np.append(limites_sup_inter, lim_sup_masa)

  valor_iter_inter = np.append(valor_iter_inter, i+1)

  print(f"IT {i+1}     || Calidad R^2 | Clase 1: {r2_c1_new:.4f} | Clase 2: {r2_c2_new:.4f} | Clase 3: {r2_c3_new:.4f} || Puntos de corte: {10**lim_inf_masa:.3f},{10**lim_sup_masa:.3f} || b0,b1: C1 = {b0_c1_interseccion:.3f},{b1_c1_interseccion:.3f} | b0,b1: C2 = {b0_c2_interseccion:.3f},{b1_c2_interseccion:.3f} | b0,b1: C3 = {b0_c3_interseccion:.3f},{b1_c3_interseccion:.3f}")

  tabla_resultados.append({
      "Iteracion": i+1,
      "R2_C1": r2_c1_new,
      "R2_C2": r2_c2_new,
      "R2_C3": r2_c3_new,
      "Lim_inf": 10**lim_inf_masa,
      "Lim_sup": 10**lim_sup_masa,
      "b0_C1": b0_c1_interseccion,
      "b1_C1": b1_c1_interseccion,
      "b0_C2": b0_c2_interseccion,
      "b1_C2": b1_c2_interseccion,
      "b0_C3": b0_c3_interseccion,
      "b1_C3": b1_c3_interseccion
      })

lim_inf_masa_gravedad = 10**lim_inf_masa
lim_sup_masa_gravedad = 10**lim_sup_masa

# Inicializamos nuestra figura
plt.figure(figsize=(10,6))

# Graficamos los puntos para cada planeta
#plt.scatter(valor_iter, calidades_c1, alpha=0.5, s=10, color='red', label='R^2:C1')
plt.plot(valor_iter_inter, calidades_c1_inter, color='red', linestyle='-', zorder=1, label=r'$R^2$ en C1', marker='o')

#plt.scatter(valor_iter, calidades_c2, alpha=0.5, s=10, color='blue', label='R^2:C2')
plt.plot(valor_iter_inter, calidades_c2_inter, color='blue', linestyle='-', zorder=1, label=r'$R^2$ en C2', marker='o')

plt.plot(valor_iter_inter, calidades_c3_inter, color='green', linestyle='-', zorder=1, label=r'$R^2$ en C3', marker='o')

# Se asignan nombres a los ejes de la gráfica
plt.xlabel("Iteración")
plt.ylabel(r"$R^{2}$")
plt.title(r"Evolución del coeficiente de determinación a lo largo de las iteraciones")

plt.legend()
plt.savefig('evolucion_coeficiente_determinacion.png')
plt.show()

tabla = pd.DataFrame(tabla_resultados)
tabla = tabla.round(4)
tabla.to_csv("iteraciones_clases_planetas.csv", index=False)
print(tabla.round(4))

# Inicializamos nuestra figura
plt.figure(figsize=(10,6))

# Graficamos los puntos para cada planeta
plt.plot(valor_iter_inter, b0_c1_inter, color='red', linestyle='-', zorder=1, label='b0 C1', marker='o')

plt.plot(valor_iter_inter, b0_c2_inter, color='blue', linestyle='-', zorder=1, label='b0 C2', marker='o')

plt.plot(valor_iter_inter, b0_c3_inter, color='green', linestyle='-', zorder=1, label='b0 C3', marker='o')

plt.plot(valor_iter_inter, b1_c1_inter, color='red', linestyle='--', zorder=1, label='b1 C1', marker='x')

plt.plot(valor_iter_inter, b1_c2_inter, color='blue', linestyle='--', zorder=1, label='b1 C2', marker='x')

plt.plot(valor_iter_inter, b1_c3_inter, color='green', linestyle='--', zorder=1, label='b1 C3', marker='x')

# Se asignan nombres a los ejes de la gráfica
plt.xlabel("Iteracion")
plt.ylabel("Coeficientes")
plt.title("b0 b1 x clase")

plt.legend()

plt.show()

# Inicializamos nuestra figura
plt.figure(figsize=(10,6))

# Graficamos los puntos para cada planeta
plt.plot(valor_iter_inter, 10**limites_inf_inter, color='red', linestyle='-', zorder=1, label='1-2', marker='o')

plt.plot(valor_iter_inter, 10**limites_sup_inter, color='blue', linestyle='-', zorder=1, label='2-3', marker='o')


# Se asignan nombres a los ejes de la gráfica
plt.xlabel("Iteracion")
plt.ylabel("M_tierra")
plt.title("Limites de clase")

plt.legend()
plt.yscale('log')

plt.show()

print(10**lim_inf_masa)
print(10**lim_sup_masa)

print(f"b0_C1: ", b0_c1_interseccion)
print(f"b1_C1: ", b1_c1_interseccion)
print(f"b0_C2: ", b0_c2_interseccion)
print(f"b1_C2: ", b1_c2_interseccion)
print(f"b0_C3: ", b0_c3_interseccion)
print(f"b1_C3: ", b1_c3_interseccion)

"""# **Grafica Comparativa**"""

# Conversión de datos del sistema TRAPPIST-1 b
trappist1_b_mass = np.log10(0.0027*mass_prop)
trappist1_b_radius = np.log10(0.09689*radius_prop)

trappist1_c_mass = np.log10(0.00434*mass_prop)
trappist1_c_radius = np.log10(0.09421*radius_prop)

trappist1_d_mass = np.log10(0.0013*mass_prop)
trappist1_d_radius = np.log10(0.0689*radius_prop)

trappist1_e_mass = np.log10(0.002*mass_prop)
trappist1_e_radius = np.log10(0.0819*radius_prop)

trappist1_f_mass = np.log10(0.0021*mass_prop)
trappist1_f_radius = np.log10(0.09323*radius_prop)

trappist1_g_mass = np.log10(0.00422*mass_prop)
trappist1_g_radius = np.log10(0.1005*radius_prop)

trappist1_h_mass = np.log10(0.001041*mass_prop)
trappist1_h_radius = np.log10(0.0674*radius_prop)

toi3288b_mass = np.log10(2.11*mass_prop)
toi3288b_radius = np.log10(1.0*radius_prop)

toi4666b_mass = np.log10(0.7*mass_prop)
toi4666b_radius = np.log10(1.11*radius_prop)

# ================================
# Comparación de regresiones
# Muller et al. vs nuestro ajuste
# Autor: Jose Miguel Mata Lopez
# ================================

# Rangos de masa
M1_muller = np.logspace(-2, np.log10(4.37), 100)
M2_muller = np.logspace(np.log10(4.37), np.log10(127), 100)
M3_muller = np.logspace(np.log10(127), 4.3, 100)

M1_ajuste = np.logspace(-2, lim_inf_masa, 100)
M2_ajuste = np.logspace(lim_inf_masa, lim_sup_masa, 100)
M3_ajuste = np.logspace(lim_sup_masa, 4.3, 100)

M1_chen = np.logspace(-2, np.log10(2.04), 100)
M2_chen = np.logspace(np.log10(2.04), np.log10(0.414*mass_prop), 100)
M3_chen = np.logspace(np.log10(0.414*mass_prop), 4.3, 100)


# -------------------------------
# Regresiones de Muller et al.
# -------------------------------
# Constantes de Müller

R1_muller = 1.02 * M1_muller**0.27
R2_muller = 0.56 * M2_muller**0.67
R3_muller = 18.6 * M3_muller**(-0.06)

# -------------------------------
# Regresiones de nuestro ajuste
# (convertidas desde log10)
# log(R) = b0 + b1 log(M)
# R = 10^b0 * M^b1
# -------------------------------

R1_nuestra = 10**(b0_c1_interseccion) * M1_ajuste**(b1_c1_interseccion)
R2_nuestra = 10**(b0_c2_interseccion) * M2_ajuste**(b1_c2_interseccion)
R3_nuestra = 10**(b0_c3_interseccion) * M3_ajuste**(b1_c3_interseccion)

R1_chen = 10**(0.0035) * M1_chen**(0.279)
R2_chen = 10**(-0.091) * M2_chen**(0.589)
R3_chen = 10**(1.258) * M3_chen**(-0.044)

# -------------------------------
# Graficar
# -------------------------------

plt.figure(figsize=(10,6))

plt.scatter(10**mass_earth, 10**radius_earth, alpha=0.5, s=10, color='lightskyblue', label="Data")
#plt.scatter(10**mass_earth_clipped, 10**radius_earth_clipped, alpha=0.5, s=10, color='lightblue', label='Datos con Sigma-Clipping')

# Muller
#plt.loglog(M1_muller, R1_muller, label="Müller et al. (2024)", color='blue', linewidth=2.5)
#plt.loglog(M2_muller, R2_muller, color='blue', linewidth=2.5)
#plt.loglog(M3_muller, R3_muller, color='blue', linewidth=2.5)


# Chen
#plt.loglog(M1_chen, R1_chen, color='green', linewidth=2.5, label="Chen & Kipping (2017)")
#plt.loglog(M2_chen, R2_chen, color='green', linewidth=2.5)
#plt.loglog(M3_chen, R3_chen, color='green', linewidth=2.5)

# Nuestro ajuste
#plt.loglog(M1_ajuste, R1_nuestra, color='red', linewidth=2.5, label="My work")
#plt.loglog(M2_ajuste, R2_nuestra, color='red', linewidth=2.5)
#plt.loglog(M3_ajuste, R3_nuestra, color='red', linewidth=2.5)

# Límites de masa entre clases
#plt.axvline(4.37, linestyle='--', color='blue', label='Limits of Müller et al.')
#plt.axvline(127, linestyle='--', color='blue')

plt.axvline(10**lim_inf_masa, linestyle='--', color='red', label='My work classification limits')
plt.axvline(10**lim_sup_masa, linestyle='--', color='red')

#plt.axvline(2.04, linestyle='--', color='green', label='Límites Chen & Kipping')
#plt.axvline(0.414*mass_prop, linestyle='--', color='green')
plt.scatter(1, 1, alpha=0.5, s=10, color='blue', label="Earth")
plt.scatter(10**trappist1_b_mass, 10**trappist1_b_radius, alpha=0.5, s=10, color='green', label="Trappist-1b")
plt.scatter(10**trappist1_c_mass, 10**trappist1_c_radius, alpha=0.5, s=10, color='red', label="Trappist-1c")
plt.scatter(10**trappist1_d_mass, 10**trappist1_d_radius, alpha=0.5, s=10, color='violet', label="Trappist-1d")
plt.scatter(10**trappist1_e_mass, 10**trappist1_e_radius, alpha=0.5, s=10, color='darkorange', label="Trappist-1e")
plt.scatter(10**trappist1_f_mass, 10**trappist1_f_radius, alpha=0.5, s=10, color='purple', label="Trappist-1f")
plt.scatter(10**trappist1_g_mass, 10**trappist1_g_radius, alpha=0.5, s=10, color='yellow', label="Trappist-1g")
plt.scatter(10**trappist1_h_mass, 10**trappist1_h_radius, alpha=0.5, s=10, color='black', label="Trappist-1h")
plt.scatter(10**toi3288b_mass, 10**toi3288b_radius, alpha=0.5, s=10, color='darkslateblue', label="TOI-3288 b")
plt.scatter(10**toi4666b_mass, 10**toi4666b_radius, alpha=0.5, s=10, color='fuchsia', label="TOI-4666 b")


# Etiquetas
plt.xlabel(r'$M_{\oplus}$', fontsize=12)
plt.ylabel(r'$R_{\oplus}$', fontsize=12)
plt.title("Regime calculated boundaries")
plt.legend()
plt.xscale('log')
plt.yscale('log')

plt.savefig('comparacion_ajustes.png', dpi=600)

plt.show()

"""# **Calidades de ajuste por separado**"""

# Definimos función para evaluar ajuste
def calidad_ajuste(x, y, b0, b1):
  stcc = 0
  sce = 0

  for i in range(len(x)):
    stcc += (y[i] - np.mean(y))**2
    sce += (y[i] - b0 - (b1*x[i]))**2
  return 1 - (sce/stcc)

#clase1_masa_orig, clase1_radio_orig, clase2_masa_orig, clase2_radio_orig, clase3_masa_orig, clase3_radio_orig

b0_c1_chen = 0.003
b1_c1_chen = 0.279

b0_c1_muller = 0.008
b1_c1_muller = 0.27

print("Calidad de ajuste Chen clase 1: ", calidad_ajuste(clase1_masa_orig, clase1_radio_orig, b0_c1_chen, b1_c1_chen))
print("Calidad de ajuste Muller clase 1: ", calidad_ajuste(clase1_masa_orig, clase1_radio_orig, b0_c1_muller, b1_c1_muller))

b0_c2_chen = -0.091
b1_c2_chen = 0.589

b0_c2_muller = -0.251
b1_c2_muller = 0.67

print("Calidad de ajuste Chen clase 2: ", calidad_ajuste(clase2_masa_orig, clase2_radio_orig, b0_c2_chen, b1_c2_chen))
print("Calidad de ajuste Muller clase 2: ", calidad_ajuste(clase2_masa_orig, clase2_radio_orig, b0_c2_muller, b1_c2_muller))

b0_c3_chen = 1.258
b1_c3_chen = -0.044

b0_c3_muller = 1.243
b1_c3_muller = -0.06

print("Calidad de ajuste Chen clase 3: ", calidad_ajuste(clase3_masa_orig, clase3_radio_orig, b0_c3_chen, b1_c3_chen))
print("Calidad de ajuste Muller clase 3: ", calidad_ajuste(clase3_masa_orig, clase3_radio_orig, b0_c3_muller, b1_c3_muller))

"""# **Calculo de Gravedad en exoplanetas**"""

def gravedad(masa, radio):
  G = 6.67e-11
  grav = (G*masa)/((radio*1000)**2)
  return grav

# Valores de la masa de la Tierra y de Júpiter en kg
e_mass = 5.97217e24
j_mass = 1898.125e24

# Proporción entre la masa de Júpiter y masa de la tierra
mass_prop = j_mass / e_mass

# Valores del radio de la Tierra y de Júpiter en km
e_radius = 6378.1366
j_radius = 71492.0
# Proporción entre el radio de Júpiter y radio de la tierra
radius_prop = j_radius / e_radius

# Cargamos la base de datos
df = pd.read_csv('/content/drive/MyDrive/Exoplanetas/base_datos.csv')
radius_earth = np.array(df['radius']*radius_prop)
mass_earth = np.array(df['mass']*mass_prop)
planet_name = np.array(df['name'])

print(gravedad(e_mass, e_radius))

print(lim_inf_masa_gravedad)
print(lim_sup_masa_gravedad)

"""# **Gravedad para mis clases**"""

clase1_masa_mine = np.array([])
clase1_radio_mine = np.array([])
clase1_nombre_mine = np.array([])
clase1_gravedad_mine = np.array([])

lim_inf_muller = 4.37

for i in range(len(radius_earth)):
  if mass_earth[i] > lim_inf_masa_gravedad and mass_earth[i] < lim_inf_muller:
    clase1_masa_mine = np.append(clase1_masa_mine, mass_earth[i])
    clase1_radio_mine = np.append(clase1_radio_mine, radius_earth[i])
    clase1_nombre_mine = np.append(clase1_nombre_mine, planet_name[i])
    gravedad_planeta = gravedad(mass_earth[i]*e_mass, radius_earth[i]*e_radius)
    clase1_gravedad_mine = np.append(clase1_gravedad_mine, gravedad_planeta)

tabla = pd.DataFrame({
    "Nombre del planeta": clase1_nombre_mine,
    "Masa (kg)": np.round(clase1_masa_mine*e_mass, 4),
    "Radio (km)": np.round(clase1_radio_mine*e_radius, 4),
    "Gravedad (m/s^2)": np.round(clase1_gravedad_mine, 4)
})


tabla.to_csv("planetas_menores.csv", index=False)
print(tabla.to_string(index=False))

limite = np.percentile(clase1_gravedad_mine, 95)  # top 5% fuera
datos_filtrados = [g for g in clase1_gravedad_mine if g <= limite]

k = 25

valores, limites_clase_masa = np.histogram(datos_filtrados, bins=k)

intervalos = [
    f"[{limites_clase_masa[i]:.3f}, {limites_clase_masa[i+1]:.3f}{']' if i == len(valores)-1 else ')'}"
    for i in range(len(valores))
]

# función para convertir masa a posición en el eje del histograma
def masa_a_posicion(m, edges):
    i = np.searchsorted(edges, m) - 1
    i = np.clip(i, 0, len(edges)-2)

    # interpolación dentro del bin
    frac = (m - edges[i]) / (edges[i+1] - edges[i])
    return i + frac


plt.figure(figsize=(7,6))
bars = plt.bar(range(len(valores)), valores)

for i in range(len(valores)):
    plt.text(i, valores[i], str(valores[i]), ha='center', va='bottom', fontsize=8.5)

plt.xlabel("Gravity (m/s^2)", size=10)
plt.ylabel("Frecuency", size=10)
plt.title("Gravity Histogram for exoplanets with M < 4.37 M_earth", size=10)

plt.xticks(range(len(intervalos)), intervalos, rotation=90)

plt.tight_layout()
plt.savefig("gravity_histogram.png", dpi=600)
plt.show()
print(len(clase1_gravedad_mine))
print(len(datos_filtrados))
print(sum(valores))

import numpy as np
import matplotlib.pyplot as plt

# Filtrar outliers (opcional pero recomendado)
limite = np.percentile(clase1_gravedad_mine, 95)
datos_filtrados = [g for g in clase1_gravedad_mine if g <= limite]

# Histograma
plt.figure(figsize=(7,6))
n, bins, patches = plt.hist(datos_filtrados, bins=25)

# Línea de la gravedad de la Tierra
plt.axvline(9.81, linestyle='--', linewidth=2,
            label="Gravedad de la Tierra")

# Etiquetas
plt.xlabel("Gravedad (m/s²)")
plt.ylabel("Frecuencia")
plt.title("Distribución de gravedad (M < 4.37 M⊕)")

# Leyenda
plt.legend()

plt.tight_layout()
plt.show()

potenciales_mass_mine = np.array([])
potenciales_radius_mine = np.array([])
potenciales_name_mine = np.array([])
potenciales_gravedad_mine = np.array([])

print("Cantidad de planetas en esta clase: ", len(clase1_masa_mine))

for i in range(len(clase1_masa_mine)):
  gravedad_planeta = gravedad(clase1_masa_mine[i]*e_mass, clase1_radio_mine[i]*e_radius)
  if gravedad_planeta >= 9 and gravedad_planeta <= 10:
    #print(f"Nombre: {clase1_nombre_mine[i]} | Gravedad: {gravedad_planeta:.2f}")
    potenciales_mass_mine = np.append(potenciales_mass_mine, clase1_masa_mine[i])
    potenciales_radius_mine = np.append(potenciales_radius_mine, clase1_radio_mine[i])
    potenciales_name_mine = np.append(potenciales_name_mine, clase1_nombre_mine[i])
    potenciales_gravedad_mine = np.append(potenciales_gravedad_mine, gravedad_planeta)

tabla = pd.DataFrame({
    "Nombre del planeta": potenciales_name_mine,
    "Masa (kg)": np.round(potenciales_mass_mine*e_mass, 4),
    "Radio (km)": np.round(potenciales_radius_mine*e_radius, 4),
    "Gravedad (m/s^2)": np.round(potenciales_gravedad_mine, 4)
})

tabla.to_csv("planetas_potenciales.csv", index=False)
print(tabla.to_string(index=False))

plt.figure(figsize=(10,6))

# Graficamos los puntos para cada planeta
plt.scatter(potenciales_mass_mine*e_mass, potenciales_radius_mine*e_radius, alpha=0.5, s=10, color='red', label="Exoplanetas con g entre 9 y 10 m/s^2")
plt.scatter(e_mass, e_radius, alpha=0.5, s=10, color='blue', label="Tierra")


# Se asignan nombres a los ejes de la gráfica
plt.xlabel("Mass (kg)")
plt.ylabel("Radius (km)")

plt.legend()
#plt.xscale('log')
#plt.yscale('log')
plt.savefig('planetas_potenciales.png', dpi=600)

plt.show()

"""# **Gravedad para clases de Müller**"""

clase1_masa_muller = np.array([])
clase1_radio_muller = np.array([])
clase1_nombre_muller = np.array([])

for i in range(len(radius_earth)):
  if mass_earth[i] < 4.37:
    clase1_masa_muller = np.append(clase1_masa_muller, mass_earth[i])
    clase1_radio_muller = np.append(clase1_radio_muller, radius_earth[i])
    clase1_nombre_muller = np.append(clase1_nombre_muller, planet_name[i])

clase1_masa_muller = clase1_masa_muller*e_mass
clase1_radio_muller = clase1_radio_muller*e_radius

potentials_mass = np.array([])
potentials_radius = np.array([])
potentials_name = np.array([])
potentials_gravity = np.array([])

for i in range(len(clase1_masa_muller)):
  gravedad_planeta = gravedad(clase1_masa_muller[i], clase1_radio_muller[i])
  if gravedad_planeta >= 9 and gravedad_planeta <= 10:
    print(f"Nombre: {clase1_nombre_muller[i]} || Gravedad: {gravedad_planeta:.2f}")
    potentials_mass = np.append(potentials_mass, clase1_masa_muller[i])
    potentials_radius = np.append(potentials_radius, clase1_radio_muller[i])
    potentials_name = np.append(potentials_name, clase1_nombre_muller[i])
    potentials_gravity = np.append(potentials_gravity, gravedad_planeta)

plt.figure(figsize=(10,6))

# Graficamos los puntos para cada planeta
plt.scatter(potentials_mass, potentials_radius, alpha=0.5, s=10, color='red', label="candidatos")
plt.scatter(e_mass, e_radius, alpha=0.5, s=10, color='blue', label="Tierra")


# Se asignan nombres a los ejes de la gráfica
plt.xlabel("Mass (M⊕)")
plt.ylabel("Radius (R⊕)")
plt.title("Planetas potenciales")

plt.legend()
#plt.xscale('log')
#plt.yscale('log')

plt.show()

G = 6.67e-11
A = G * (1.138875E+23/(1996.0566*1000)**2)
print(A)

print(226-109)

